name: Release Pyromod

on:
  push:
    tags:
      - v**

jobs:
  build-pyromod:
    runs-on: ubuntu-latest
    env:
      MOD_NAME: godseye
      MOD_VERSION: ${{ github.ref_name }}
    steps:
    - uses: actions/checkout@v3
    - run: echo "MOD_VERSION=${MOD_VERSION:1}" >> $GITHUB_ENV
    - uses:  0ad-matters/gh-action-build-pyromod@v1.2
      with:
        name: ${{ env.MOD_NAME }}
        version: ${{ env.MOD_VERSION }}
      id: build-pyromod
    - run: |
        OUTPUT_FILE="$MOD_NAME-${MOD_VERSION}.pyromod"
        cd output
        sha256sum $OUTPUT_FILE > ${OUTPUT_FILE}.sha256sum
    - name: Release PyroMod
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: True
        prerelease: False
        artifacts: "output/${{ env.MOD_NAME }}*.*"
        token: ${{ secrets.GITHUB_TOKEN }}
        omitNameDuringUpdate: True
        omitBodyDuringUpdate: True
